"""
Group 1 — Official JSON Data Contracts
These schemas define the exact data format shared with Group 2 and Group 3.
Any change here must be communicated to all groups immediately.
Version: 1.0.0
Date: 15 May 2026
"""

# ── Contract 1: Outcome Object ────────────────────────────────────
# Used by: Group 1 (generator), Group 2 (mapper), Group 3 (UI)
OUTCOME_OBJECT_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "OutcomeObject",
    "description": "A single AI-generated learning outcome with rules engine results",
    "type": "object",
    "required": ["id", "type", "text", "bloom_level", "assessment_suggestion",
                 "confidence_est", "flags", "domain_tags", "source_course_id",
                 "generated_by"],
    "properties": {
        "id":                  {"type": "string",  "description": "Unique outcome ID e.g. OC001"},
        "type":                {"type": "string",  "enum": ["course_outcome", "program_outcome", "unit_outcome"]},
        "text":                {"type": "string",  "minLength": 8,  "maxLength": 500},
        "bloom_level":         {"type": "string",  "enum": ["remember","understand","apply","analyze","evaluate","create"]},
        "assessment_suggestion":{"type": "string"},
        "confidence_est":      {"type": "number",  "minimum": 0.0, "maximum": 1.0},
        "flags":               {"type": "array",   "items": {"type": "string"}},
        "domain_tags":         {"type": "array",   "items": {"type": "string"}},
        "source_course_id":    {"type": "string"},
        "generated_by":        {"type": "string",  "description": "Model version e.g. llama3.1:8b"},
    }
}

# ── Contract 2: Course + Units Schema ────────────────────────────
# Used by: Group 1 (syllabus generator), Group 3 (UI display)
COURSE_UNITS_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CourseUnitsSchema",
    "description": "Full course with unit-wise syllabus",
    "type": "object",
    "required": ["course_id", "title", "description", "credits", "units"],
    "properties": {
        "course_id":   {"type": "string"},
        "title":       {"type": "string"},
        "description": {"type": "string"},
        "credits":     {"type": "integer", "minimum": 1, "maximum": 10},
        "units": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["unit_id","unit_title","unit_objectives",
                             "unit_outcomes","assessments","readings"],
                "properties": {
                    "unit_id":          {"type": "string"},
                    "unit_title":       {"type": "string"},
                    "unit_objectives":  {"type": "array", "items": {"type": "string"}},
                    "unit_outcomes":    {"type": "array", "items": {"type": "string"}},
                    "assessments":      {"type": "array", "items": {"type": "string"}},
                    "readings":         {"type": "array", "items": {"type": "string"}},
                }
            }
        },
        "textbooks":         {"type": "array", "items": {"type": "string"}},
        "youtube_resources": {"type": "array", "items": {"type": "string"}},
    }
}

# ── Contract 3: Mapping Response Schema ──────────────────────────
# Generated by: Group 2 (mapper)
# Consumed by:  Group 3 (mapping canvas UI)
MAPPING_RESPONSE_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "MappingResponseSchema",
    "description": "Group 2 output — CO to PO mapping candidates",
    "type": "object",
    "required": ["lo_id", "candidates"],
    "properties": {
        "lo_id": {"type": "string", "description": "Learning Outcome ID being mapped"},
        "candidates": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["po_id","similarity_score","classifier_prob",
                             "keywords_matched","explanation"],
                "properties": {
                    "po_id":            {"type": "string"},
                    "similarity_score": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                    "classifier_prob":  {"type": "number", "minimum": 0.0, "maximum": 1.0},
                    "keywords_matched": {"type": "array", "items": {"type": "string"}},
                    "explanation":      {"type": "string"},
                }
            }
        }
    }
}

# ── Contract 4: Training Labels Schema ───────────────────────────
# Generated by: Group 1 (review system)
# Consumed by:  Group 2 (BERT retraining)
TRAINING_LABEL_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "TrainingLabelSchema",
    "description": "Faculty-verified training labels for Group 2 BERT retraining",
    "type": "object",
    "required": ["is_valid","was_edited","original_text","approved_text","bloom_level"],
    "properties": {
        "is_valid":      {"type": "boolean", "description": "True if accepted or edited"},
        "was_edited":    {"type": "boolean", "description": "True if faculty modified text"},
        "original_text": {"type": "string"},
        "approved_text": {"type": "string"},
        "bloom_level":   {"type": "string"},
    }
}

# ── Contract 5: Programme Schema ─────────────────────────────────
# Generated by: Group 1 (programme generator)
# Consumed by:  Group 2 (CAM builder), Group 3 (dashboard)
PROGRAMME_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ProgrammeSchema",
    "description": "Complete programme with PEOs, POs and PSOs",
    "type": "object",
    "required": ["programme_name","peos","pos","psos"],
    "properties": {
        "programme_name": {"type": "string"},
        "peos": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["peo_id","text","focus_area"],
                "properties": {
                    "peo_id":     {"type": "string"},
                    "text":       {"type": "string"},
                    "focus_area": {"type": "string"},
                }
            }
        },
        "pos": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["po_id","title","text"],
                "properties": {
                    "po_id": {"type": "string"},
                    "title": {"type": "string"},
                    "text":  {"type": "string"},
                }
            }
        },
        "psos": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["pso_id","text","domain"],
                "properties": {
                    "pso_id": {"type": "string"},
                    "text":   {"type": "string"},
                    "domain": {"type": "string"},
                }
            }
        }
    }
}

# ── All contracts in one dict ─────────────────────────────────────
ALL_CONTRACTS = {
    "version":          "1.0.0",
    "last_updated":     "2026-05-15",
    "group":            "Group 1",
    "OutcomeObject":    OUTCOME_OBJECT_SCHEMA,
    "CourseUnits":      COURSE_UNITS_SCHEMA,
    "MappingResponse":  MAPPING_RESPONSE_SCHEMA,
    "TrainingLabel":    TRAINING_LABEL_SCHEMA,
    "Programme":        PROGRAMME_SCHEMA,
}