import json
import os

co_texts = [
    "Build intelligent agents for search and games",
    "Solve AI problems through programming with Python.",
    "Learn optimization and inference algorithms for model learning.",
    "Design and develop programs for an agent to learn and act in a structured environment.",
    "Possess the ability to apply AI techniques to solve problems of Game Playing, Expert Systems and machine learning.",
    "Have a broad understanding of the capabilities and limitations of current natural language technologies.",
    "Able to model linguistic phenomena with formal grammars.",
    "Be able to Design, implement and test algorithms for NLP problems.",
    "Understand the mathematical and linguistic foundations underlying approaches to the various areas in NLP.",
    "Able to apply NLP techniques to design real world NLP applications such as machine translation, text categorization, text summarization, information extraction...etc.",
    "Learn the basics of learning problems with hypothesis and version spaces.",
    "Understand the machine learning algorithms as supervised learning and unsupervised learning and Apply and analyze the various algorithms of supervised and unsupervised learning.",
    "Analyze the concept of neural networks for learning linear and non-linear activation functions.",
    "Learn the concepts in tree, probability and graphical based models and methods.",
    "Understand the fundamental concepts of Genetic Algorithm and Analyze and design the genetic algorithms for optimization engineering problems.",
    "Understand the basic concept of walk, path and circuit in a graph.",
    "Perform the basic operation of Euler graph and digraph",
    "Discuss the various spanning trees algorithms.",
    "Understand the concept of edge connectivity, vertex connectivity and separable graphs.",
    "Derive the relations between the reduced incidence matrix, the fundamental cycle matrix, and the fundamental cut-set matrix of a graph G.",
    "Identify appropriate software design model based on requirement analysis.",
    "Formulate Software Requirements Specification (SRS) reports for the real world application.",
    "Translate a specification into a design and identify the components to build the architecture.",
    "Plan a software engineering process to account for quality issues and non-functionalrequirements.",
    "Estimate the work to be done, resources required and the schedule for a software project plan.",
    "Have a fundamental knowledge of the basic concepts of probability.",
    "Have a well-founded knowledge of various probability distributions which can describe real-life phenomena.",
    "Acquire skills in estimating expected values of variables and handling situations involving more than one random variable and functions of random variables.",
    "Understand the stochastic processes and phenomena which evolve concerning time in a probabilistic manner.",
    "Expose the basic characteristic features of Markov chains, queuing systems and queuing models.",
    "Understand research problems and challenges in fault tolerance computing.",
    "Identify the state-of-the-art techniques and tools to address research problems and challenges.",
    "Develop strong technical reviewing, writing, and presentation skills.",
    "Design more reliable systems that can tolerate S/W faults.",
    "Design more reliable systems that can tolerate H/W faults.",
    "Grasp a fundamental understanding of goals, components, and evolution of real time systems.",
    "Explain the concepts of real time scheduling.",
    "Learn the scheduling policies of modern operating systems.",
    "Understand the resource access control techniques in real time systems.",
    "Understand the concept of real time communication.",
    "Acquire the theoretical and conceptual foundations of distributed computing.",
    "Conceptualize the ideas of distributed operating systems and their issues.",
    "Understand the issues involved in distributed resource environment.",
    "Realize the importance of transaction and deadlock detection and how to recover the system from deadlocks.",
    "Explore the principles of fault tolerance and its protocols.",
    "Write relational algebra expressions for that query and optimize the developed expressions.",
    "Design the databases using E-R method and normalization.",
    "Understand the concepts of function dependencies and various normal forms.",
    "Understand the concept of transaction atomicity, consistency, isolation, and durability properties in context of real life examples.",
    "Develop the understanding of query processing and advanced databases.",
    "Implement the Artificial Intelligence techniques for building well engineered and efficient intelligent systems.",
    "Describe the nature of AI problem and provide the solution as a particular type.",
    "Learn optimization and inference algorithms for model learning.",
    "Solve game challenging problems",
    "Design and develop programs for an agent to learn and act in a structured environment.",
    "Use the NLTK and spaCy toolkit for NLP Programming.",
    "Analyze various corpora for developing programs.",
    "Develop various pre-processing techniques for a given corpus.",
    "Develop programming logic using NLTK functions.",
    "Build applications using various NLP techniques for a given corpus. (L6)",
    "Make use of Data sets in implementing the machine learning algorithms.",
    "Understand the implementation procedures for the machine learning algorithms.",
    "Design Java/Python programs for various Learning algorithms.",
    "Apply appropriate data sets to the Machine Learning algorithms.",
    "Identify and apply Machine Learning algorithms to solve real world problems.",
    "Understand organizational issues and their impact on the organization and employees.",
    "Identify industrial problems and suggest possible solutions.",
    "Relate, apply and adapt relevant knowledge, concepts and theories within an industrial organization, practice and ethics.",
    "Apply technical knowledge in an industry to solve real world problems.",
    "Demonstrate effective group communication, presentation, self-management, and report writing skills.",
    "Understand the basic knowledge and salient features of Indian Constitution.",
    "Identify and explore the basic features and modalities about Indian constitution.",
    "Discusses the essence of Union and its territories, Citizenship, Fundamental Rights, DPSP and Fundamental Duties.",
    "Differentiate and relate the functioning of Indian parliamentary system at the center and state level.",
    "Differentiate different aspects of Indian Legal System and its related bodies.",
    "Understand the concept of Traditional knowledge and its importance.",
    "Know the need and importance of protecting traditional knowledge.",
    "Know the various enactments related to the protection of traditional knowledge.",
    "Understand the concepts of Intellectual property to protect the traditional knowledge.",
    "Know the contribution of scientists of different areas.",
    "Understand the theoretical foundations of neural networks, including perceptrons, activation functions, and backpropagation.",
    "Learn to design and implement neural network models for solving classification, regression, and other tasks.",
    "Explore advanced neural network architectures and techniques, such as convolutional neural networks (CNNs), recurrent neural networks (RNNs), and deep learning.",
    "Gain practical experience through hands-on programming assignments and projects.",
    "Analyze and interpret neural network models and their performance.",
    "Students can understand the definitions, concepts and components of Rural Development.",
    "Students will know the importance, structure, significance, resources of Indian rural economy.",
    "Students will have a clear idea about the area development programmes and its impact.",
    "Students will be able to acquire knowledge about rural entrepreneurship.",
    "Students will be able to understand about the using of different methods for human resource planning.",
    "Understand project characteristics and various stages of a project.",
    "Understand the conceptual clarity about project organization and feasibility analyses – Market, Technical, Financial and Economic.",
    "Analyze the learning and understand techniques for Project planning, scheduling and Execution Control.",
    "Describe Entrepreneurship, Examine role of entrepreneur in economic development.",
    "Describe the steps to establish an enterprise.",
    "list and explain the basic elements of industrial robots",
    "Analyze robot kinematics and its control methods.",
    "classifythe various sensors used in robots for better performance.",
    "summarize various industrial and non-industrial applications of robots.",
    "Understand concept of managerial decision systems and outline its various phases.",
    "Demonstrate DSS components and identify sources of data for business intelligence.",
    "Categorize the methodologies involved in DSS development.",
    "Analyze evolution of enterprise DSS and knowledge management initiatives.",
    "Infer AI and Expert systems evolution and probe advances in intelligent support systems.",
    "Explain the principles underlying Evolutionary Computation in general and Genetic Algorithms in particular.",
    "Get acquainted with the theoretical foundation of genetic algorithms.",
    "Apply Evolutionary Computation Methods to find solutions to complex problems",
    "Analyze and experiment with parameter choices in the use of Evolutionary Computation",
    "Summarize current research in Genetic Algorithms and Evolutionary Computing",
    "Interpret the contribution of data warehousing and data mining to the decision-support level of organizations",
    "Evaluate different models used for OLAP and data preprocessing",
    "Categorize and carefully differentiate between situations for applying different data-mining techniques: frequent pattern mining, association, correlation, classification, prediction, and cluster and outlier analysis",
    "Design, implement and evaluate the performance of different data-mining algorithms",
    "Propose data-mining solutions for different applications",
    "Understand Blockchain technology.",
    "Develop Blockchain based solutions and write smart contract using Hyperledger Fabric and Ethereum frameworks.",
    "Build and deploy Blockchain application for on premise and cloud-based architecture.",
    "Develop the concepts for safe use of crypto currency",
    "Integrate ideas from various domains and implement them using Blockchain technology",
    "Demonstrate the mathematical foundations needed for data science.",
    "Collect, explore, clean and manipulate data.",
    "Demonstrate the basic concepts of machine learning.",
    "Implement models such as k-nearest Neighbors, Naive Bayes, linear and logistic regression, decision trees, neural networks and clustering.",
    "Build data science applications using Python based toolkits.",
    "Identify the various attacks and its issues.",
    "Learn usage of cryptographic algorithms for avoiding basic level threats.",
    "Comprehend the issues involved in Integrity, Authentication and Key Management techniques.",
    "Realize the importance of user authentication and Kerberos concepts.",
    "Acquire the knowledge of network and system security domain.",
    "Understand the basic ideas of fuzzy sets, operations and properties of fuzzy sets, and fuzzy relations.",
    "Understand the basic features of membership functions, fuzzification process and defuzzification process.",
    "Design fuzzy rule-based system.",
    "Know about combining fuzzy set theory with probability to handle random and non-random uncertainty, and the decision-making process.",
    "Gain the knowledge about fuzzy C-Means clustering.",
    "Impart the knowledge of cloud computing and technologies, issues in cloud computing etc.",
    "Design and develop cloud and implement various services on cloud.",
    "To develop an understanding of virtualization technology and its different dimensions.",
    "Investigate the issues and challenges in implementing cloud security.",
    "Compare and contrast various open and proprietary cloud platforms",
    "illustrate the steps involved in predictive analytics and modeling.",
    "demonstrate data cleaning procedures and preprocessing.",
    "examine association rule mining and descriptive modeling for prediction.",
    "utilize Machine learning in predictive analytics.",
    "discover the role of ensembles and text mining methods.",
    "apply predictive modeling for solving real world problems.",
    "Setup R Programming Environment.",
    "Understand and use R – Data types.",
    "Understand and use R – Data Structures.",
    "Develop programming logic using R – Packages.",
    "Analyze data sets using R – programming capabilities",
    "Prepare and develop practically applicable business plan for an innovative project with consideration of addressed issues.",
    "Develop the sub-skills required for business plans of innovation projects presentation and group discussions.",
    "Acquire the soft skills and interpersonal skills which will help them in their workplace needed for these functions.",
    "Develop planning skills of the innovative projects and business ideas in order to improve professional competencies.",
    "Make presentation on the topic, answer the queries/questions that come forward, clarify, and supplement if necessary, and submit a report."
]

mock_los = [{"id": f"LO-{i+1}", "text": text} for i, text in enumerate(co_texts)]

# 1. Update mock_los.json
with open("data/mock_los.json", "w", encoding="utf-8") as f:
    json.dump(mock_los, f, indent=2)

# 2. Remove syllabus_data.json so generate_labeled_pairs.py picks up the new mock_los.json
if os.path.exists("data/syllabus_data.json"):
    os.remove("data/syllabus_data.json")

print("Created data/mock_los.json with", len(mock_los), "COs.")
